INHERIT: utils/mkdocs-base.yml

site_name: 香山开源处理器设计文档
repo_url: https://github.com/OpenXiangShan/XiangShan-Design-Doc
repo_name: XiangShan-Design-Doc

nav:
  - 前端:
    - 取指目标队列: frontend/FTQ/FTQ.md
    - 取指令单元:
      - 整体设计: frontend/IFU/IFU.md
      - 预译码器: frontend/IFU/PreDecoder.md
    - 指令缓存:
      - 整体设计: frontend/ICache/ICache.md
      - MainPipe: frontend/ICache/MainPipe.md
      - IPrefetchPipe: frontend/ICache/IPrefetchPipe.md
      - WayLookup: frontend/ICache/WayLookup.md
      - MissUnit: frontend/ICache/MissUnit.md
      - Replacer: frontend/ICache/Replacer.md
      - CtrlUnit: frontend/ICache/CtrlUnit.md
  - 访存:
    - 访存流水线 LSU:
      - memblock/LSU/index.md
      - LSQ:
        - memblock/LSU/LSQ/index.md
        - 访存队列 LSQ: memblock/LSU/LSQ/LSQ.md
        - VirtualLoadQueue.md: memblock/LSU/LSQ/VirtualLoadQueue.md
        - LoadQueueRAR.md: memblock/LSU/LSQ/LoadQueueRAR.md
        - LoadQueueRAW.md: memblock/LSU/LSQ/LoadQueueRAW.md
        - Load重发队列LoadQueueReplay: memblock/LSU/LSQ/LoadQueueReplay.md
        - LqExceptionBuffer.md: memblock/LSU/LSQ/LqExceptionBuffer.md
        - Store队列StoreQueue: memblock/LSU/LSQ/StoreQueue.md
      - LoadUnit: memblock/LSU/LoadUnit.md
      - SBuffer.md: memblock/LSU/SBuffer.md
      - StdExeUnit.md: memblock/LSU/StdExeUnit.md
      - StoreUnit.md: memblock/LSU/StoreUnit.md
    - 数据缓存:
      - memblock/DCache/index.md
      - 数据高速缓存DCache: memblock/DCache/DCache.md
      - Load访存流水线LoadPipe: memblock/DCache/LoadPipe.md
      - 缺失队列MissQueue: memblock/DCache/MissQueue.md
      - Probe队列ProbeQueue: memblock/DCache/ProbeQueue.md
      - 主流水线MainPipe: memblock/DCache/MainPipe.md
      - 写回队列WritebackQueue: memblock/DCache/WritebackQueue.md
      - 错误处理与自定义故障注入指令: memblock/DCache/Error.md
    - 内存管理单元 MMU:
      - memblock/MMU/index.md
      - L1TLB: memblock/MMU/L1TLB.md
      - Repeater: memblock/MMU/Repeater.md
      - L2TLB:
        - memblock/MMU/L2TLB/index.md
        - Page Cache: memblock/MMU/L2TLB/PageCache.md
        - Page Table Walker: memblock/MMU/L2TLB/PTW.md
        - Last Level Page Table Walker: memblock/MMU/L2TLB/LLPTW.md
        - Hypervisor Page Table Walker: memblock/MMU/L2TLB/HPTW.md
        - Miss Queue: memblock/MMU/L2TLB/MissQueue.md
        - Prefetcher: memblock/MMU/L2TLB/Prefetcher.md
      - PMP & PMA: memblock/MMU/PMP-PMA.md
